#!/usr/bin/python
# encoding: utf-8

import sys
import os
from os import path

if 1 < len(sys.argv):
    ROOT = sys.argv[1]
else:
    ROOT = path.realpath(path.dirname(sys.argv[0]) + '/../../db')
if not path.exists(ROOT):
    sys.exit('Invalid path of DB folder.')

novels = [i for i in os.listdir(ROOT) if path.isdir(ROOT + '/' + i)]
if 1 > len(novels):
    sys.exit('No novels found.')
print '> found %d novels:' % len(novels)

for novel in novels:
    print '\n' + novel + '\n----\n'
    pages = [i[0:-4] for i in os.listdir(ROOT + '/' + novel) if '.xml' == i[-4:]]
    pages.sort(lambda x, y: -1 if 'toc' == x else 1 if 'toc' == y else cmp(int(x), int(y)))
    for page in pages:
        print '*' + ' ' * (5 - len(page)) + page + '.xml:',
        file = ROOT + '/' + novel + '/' + page + '.xml'
        try:
            with open(file) as fh:
                data = fh.read(100)
                if -1 < data.find('<?xml-stylesheet '):
                    print 'ok'
                    fh.close()
                    continue
                data += fh.read()
                fh.close()
            pos = 20 + data.find(' standalone="yes"?>')
            data = data[0:pos] + \
                '<?xml-stylesheet type="text/xsl" href="../' + \
                ('toc' if 'toc' == page else 'chapter') + '.xslt"?>\n' + \
                data[pos:]
            mtime = path.getmtime(file)
            with open(file, 'w') as fh:
                fh.write(data)
                fh.close()
            os.utime(file, (mtime, mtime))
            print 'succeed'
        except:
            print 'failed'
